"""Stable constants shared by the remote-control modules."""

GAME_PACKAGE = "jp.co.drecom.wizardry.daphne"
DEFAULT_GAME_ACTIVITY = (
    "jp.co.drecom.wizardry.daphne/"
    "com.google.firebase.MessagingUnityPlayerActivity"
)
BOT_API_ORIGIN = "https://api.telegram.org"

POLL_TIMEOUT_SECONDS = 25
LONG_POLL_HTTP_TIMEOUT_SECONDS = 35
SHORT_HTTP_TIMEOUT_SECONDS = 15
SEND_BACKOFF_SECONDS = (1, 2, 5, 10, 30)
SERVICE_THREAD_JOIN_TIMEOUT_SECONDS = 36
SENT_KEY_CACHE_SIZE = 4096
MAX_PENDING_MESSAGES = 256

REMOTE_STOP_TIMEOUT_SECONDS = 600
TOWN_CONFIRM_TIMEOUT_SECONDS = 10
EXIT_MENU_TIMEOUT_SECONDS = 30
TITLE_LOAD_TIMEOUT_SECONDS = 120
MAX_EXIT_MENU_BACK_PRESSES = 3
INPUT_COOLDOWN_SECONDS = 2
EDGE_TO_TOWN_TIMEOUT_SECONDS = 60
QUEST_RTT_TIMEOUT_SECONDS = 180

LOGIN_ATTEMPT_TIMEOUT_SECONDS = 180
MAX_LOGIN_ATTEMPTS = 2
APP_START_SETTLE_SECONDS = 10
STABLE_FRAME_COUNT = 2
STABLE_FRAME_INTERVAL_SECONDS = 0.5
DIALOGUE_ADVANCE_INTERVAL_SECONDS = 0.35

FALLBACK_SUBPROCESS_TIMEOUT_SECONDS = 7
FALLBACK_VERIFY_TIMEOUT_SECONDS = 5
FALLBACK_WAIT_TIMEOUT_SECONDS = 15
WORKER_EXIT_TIMEOUT_SECONDS = 15
GUI_CONNECTION_TEST_TIMEOUT_SECONDS = 20
CONTROLLER_TICK_MILLISECONDS = 100
WORKER_POLL_MILLISECONDS = 50
MAX_EVENTS_PER_TICK = 50
HANDOFF_TARGET_7000G = "7000G"

SUPPORTED_TOWN_PATTERNS = (
    "Inn",
    "City_RoyalCityLuknalia",
    "City_fortress",
    "City_DHI",
    "City_portTownGrandLegion",
)

TO_TITLE_PRIMARY_ROI = ((300, 820, 300, 170),)
TO_TITLE_DIALOG_ROI = ((180, 650, 540, 500),)
TITLE_LOGO_ROI = ((0, 0, 900, 960),)
TITLE_TAP_ROI = ((0, 800, 900, 800),)
STARTUP_DISCLAIMER_ROI = ((150, 450, 600, 350),)
DIALOGUE_NEXT_ROI = ((750, 1400, 150, 200),)
TO_TITLE_PRIMARY_THRESHOLD = 0.86
TO_TITLE_DIALOG_THRESHOLD = 0.92
TITLE_TEMPLATE_THRESHOLD = 0.88
DIALOGUE_NEXT_THRESHOLD = 0.80

STARTUP_DISCLAIMER_TEMPLATE = "startupDisclaimer"
TITLE_LOGO_TEMPLATE = "titlelogo"
TITLE_TAP_TEMPLATE = "tabtostart"
TITLE_TAP_FALLBACK_POSITION = (450, 1367)
